// <auto-generated />
using HTActive.Common;
using HTActive.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace HTActive.Web.Migrations
{
    [DbContext(typeof(InstanceEntities))]
    [Migration("20170915103325_thuan_000014")]
    partial class thuan_000014
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("HTActive.Entities.Claim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("Claim");
                });

            modelBuilder.Entity("HTActive.Entities.ContentContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .HasMaxLength(512);

                    b.Property<string>("Button")
                        .HasMaxLength(512);

                    b.Property<string>("ContactPageTitle")
                        .HasMaxLength(512);

                    b.Property<string>("ContactUs")
                        .HasMaxLength(512);

                    b.Property<string>("Content")
                        .HasMaxLength(512);

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(512);

                    b.Property<string>("HTEmail")
                        .HasMaxLength(512);

                    b.Property<int?>("Language");

                    b.Property<string>("Loading")
                        .HasMaxLength(512);

                    b.Property<string>("Mail")
                        .HasMaxLength(512);

                    b.Property<string>("MailHolder")
                        .HasMaxLength(512);

                    b.Property<string>("Message")
                        .HasMaxLength(512);

                    b.Property<string>("MessageHolder")
                        .HasMaxLength(512);

                    b.Property<string>("Name")
                        .HasMaxLength(512);

                    b.Property<string>("NameHolder")
                        .HasMaxLength(512);

                    b.Property<string>("Phone")
                        .HasMaxLength(512);

                    b.Property<string>("Received")
                        .HasMaxLength(512);

                    b.Property<string>("Skype")
                        .HasMaxLength(512);

                    b.Property<string>("Sorry")
                        .HasMaxLength(512);

                    b.Property<string>("SorryMessage")
                        .HasMaxLength(512);

                    b.Property<string>("Subject")
                        .HasMaxLength(512);

                    b.Property<string>("SubjectHolder")
                        .HasMaxLength(512);

                    b.Property<string>("Thanks")
                        .HasMaxLength(512);

                    b.Property<string>("ThanksMessage")
                        .HasMaxLength(512);

                    b.Property<string>("Title")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.ToTable("ContentContact");
                });

            modelBuilder.Entity("HTActive.Entities.ContentFooter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AboutUsHref")
                        .HasMaxLength(512);

                    b.Property<string>("AboutUsText")
                        .HasMaxLength(512);

                    b.Property<string>("Address")
                        .HasMaxLength(512);

                    b.Property<string>("Address2")
                        .HasMaxLength(512);

                    b.Property<string>("Content1")
                        .HasMaxLength(512);

                    b.Property<string>("CopyRight")
                        .HasMaxLength(512);

                    b.Property<string>("Email")
                        .HasMaxLength(512);

                    b.Property<string>("Facebook")
                        .HasMaxLength(512);

                    b.Property<string>("Flickr")
                        .HasMaxLength(512);

                    b.Property<string>("GooglePlus")
                        .HasMaxLength(512);

                    b.Property<int?>("Language");

                    b.Property<string>("LinkedIn")
                        .HasMaxLength(512);

                    b.Property<string>("Mobile")
                        .HasMaxLength(512);

                    b.Property<string>("Phone")
                        .HasMaxLength(512);

                    b.Property<string>("Pinterest")
                        .HasMaxLength(512);

                    b.Property<string>("Skype")
                        .HasMaxLength(512);

                    b.Property<string>("Slogan")
                        .HasMaxLength(512);

                    b.Property<string>("Twitter")
                        .HasMaxLength(512);

                    b.Property<string>("YouTube")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.ToTable("ContentFooter");
                });

            modelBuilder.Entity("HTActive.Entities.ContentIndex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AboutUsContent")
                        .HasMaxLength(512);

                    b.Property<string>("AboutUsLeftContent")
                        .HasMaxLength(512);

                    b.Property<string>("AboutUsLeftSrc")
                        .HasMaxLength(512);

                    b.Property<string>("AboutUsLeftSubContent")
                        .HasMaxLength(512);

                    b.Property<string>("AboutUsLeftTitle")
                        .HasMaxLength(512);

                    b.Property<string>("AboutUsLeftUrl")
                        .HasMaxLength(512);

                    b.Property<string>("AboutUsTitle")
                        .HasMaxLength(512);

                    b.Property<string>("ButtonContact")
                        .HasMaxLength(512);

                    b.Property<string>("ButtonReadMore")
                        .HasMaxLength(512);

                    b.Property<string>("ContactContent")
                        .HasMaxLength(512);

                    b.Property<string>("ContactTitle")
                        .HasMaxLength(512);

                    b.Property<string>("FeatureContent")
                        .HasMaxLength(512);

                    b.Property<string>("FeatureTitle")
                        .HasMaxLength(512);

                    b.Property<string>("HomePageTitle")
                        .HasMaxLength(512);

                    b.Property<int?>("Language");

                    b.Property<string>("PolicyContent")
                        .HasMaxLength(512);

                    b.Property<string>("PolicyTitle")
                        .HasMaxLength(512);

                    b.Property<string>("WhyChooseContent")
                        .HasMaxLength(512);

                    b.Property<string>("WhyChooseTitle")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.ToTable("ContentIndex");
                });

            modelBuilder.Entity("HTActive.Entities.ContentIndexAboutUsRight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content")
                        .HasMaxLength(512);

                    b.Property<int?>("ContentIndexId");

                    b.Property<string>("Icon")
                        .HasMaxLength(512);

                    b.Property<int?>("Priority");

                    b.Property<string>("Title")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.HasIndex("ContentIndexId");

                    b.ToTable("ContentIndexAboutUsRight");
                });

            modelBuilder.Entity("HTActive.Entities.ContentIndexFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content")
                        .HasMaxLength(512);

                    b.Property<int?>("ContentIndexId");

                    b.Property<string>("Icon")
                        .HasMaxLength(512);

                    b.Property<int?>("Priority");

                    b.Property<string>("Title")
                        .HasMaxLength(512);

                    b.Property<string>("Url")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.HasIndex("ContentIndexId");

                    b.ToTable("ContentIndexFeature");
                });

            modelBuilder.Entity("HTActive.Entities.ContentIndexTopSlide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ContentIndexId");

                    b.Property<string>("MainImageAlt")
                        .HasMaxLength(512);

                    b.Property<string>("MainImageSrc")
                        .HasMaxLength(512);

                    b.Property<int?>("Priority");

                    b.Property<string>("RightImageAlt")
                        .HasMaxLength(512);

                    b.Property<string>("RightImageSrc")
                        .HasMaxLength(512);

                    b.Property<string>("SlideContents")
                        .HasMaxLength(512);

                    b.Property<string>("SlideFooter")
                        .HasMaxLength(512);

                    b.Property<string>("SlideTitle")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.HasIndex("ContentIndexId");

                    b.ToTable("ContentIndexTopSlide");
                });

            modelBuilder.Entity("HTActive.Entities.ContentIndexWhyChoose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content")
                        .HasMaxLength(512);

                    b.Property<int?>("ContentIndexId");

                    b.Property<int?>("Priority");

                    b.Property<string>("Src")
                        .HasMaxLength(512);

                    b.Property<string>("SubTitle")
                        .HasMaxLength(512);

                    b.Property<string>("Title")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.HasIndex("ContentIndexId");

                    b.ToTable("ContentIndexWhyChoose");
                });

            modelBuilder.Entity("HTActive.Entities.ContentMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ContentFooterId");

                    b.Property<string>("Link")
                        .HasMaxLength(512);

                    b.Property<int?>("Priority");

                    b.Property<string>("Tab")
                        .HasMaxLength(512);

                    b.Property<string>("Text")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.HasIndex("ContentFooterId");

                    b.ToTable("ContentMenu");
                });

            modelBuilder.Entity("HTActive.Entities.ContentNews", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ByText")
                        .HasMaxLength(512);

                    b.Property<int>("Language");

                    b.Property<string>("ReadMoreText")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.ToTable("ContentNews");
                });

            modelBuilder.Entity("HTActive.Entities.ContentProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ButtonReadMore")
                        .HasMaxLength(512);

                    b.Property<string>("Content")
                        .HasMaxLength(512);

                    b.Property<string>("Header1")
                        .HasMaxLength(512);

                    b.Property<string>("Header1Content")
                        .HasMaxLength(512);

                    b.Property<string>("Header2")
                        .HasMaxLength(512);

                    b.Property<string>("Header2Content")
                        .HasMaxLength(512);

                    b.Property<string>("Header3")
                        .HasMaxLength(512);

                    b.Property<string>("Header3Content")
                        .HasMaxLength(512);

                    b.Property<int>("Language");

                    b.Property<string>("ProductPageTitle")
                        .HasMaxLength(512);

                    b.Property<string>("Title")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.ToTable("ContentProduct");
                });

            modelBuilder.Entity("HTActive.Entities.ContentService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content")
                        .HasMaxLength(512);

                    b.Property<int>("Language");

                    b.Property<string>("ServicePageTitle")
                        .HasMaxLength(512);

                    b.Property<string>("Title")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.ToTable("ContentService");
                });

            modelBuilder.Entity("HTActive.Entities.ContentServicePartition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content")
                        .HasMaxLength(512);

                    b.Property<int?>("ContentServiceId");

                    b.Property<int?>("Priority");

                    b.Property<int>("ServiceType");

                    b.Property<string>("Title")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.HasIndex("ContentServiceId");

                    b.ToTable("ContentServicePartition");
                });

            modelBuilder.Entity("HTActive.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("S3FileKey")
                        .HasMaxLength(256);

                    b.Property<string>("Url")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("HTActive.Entities.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Priority");

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("HTActive.Entities.NewsLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author")
                        .HasMaxLength(512);

                    b.Property<string>("CoverSource")
                        .HasMaxLength(512);

                    b.Property<int?>("CoverType");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("Description")
                        .HasMaxLength(512);

                    b.Property<string>("Html")
                        .HasMaxLength(4000);

                    b.Property<int?>("Language");

                    b.Property<int?>("NewsId");

                    b.Property<string>("Title")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.HasIndex("NewsId");

                    b.ToTable("NewsLanguage");
                });

            modelBuilder.Entity("HTActive.Entities.NewsLanguageImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Alt");

                    b.Property<int>("NewsLanguageId");

                    b.Property<int?>("Priority");

                    b.Property<string>("Src");

                    b.HasKey("Id");

                    b.HasIndex("NewsLanguageId");

                    b.ToTable("NewsLanguageImage");
                });

            modelBuilder.Entity("HTActive.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Priority");

                    b.Property<int?>("ProductType");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("HTActive.Entities.ProductLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(512);

                    b.Property<string>("DescriptionDetailHeader")
                        .HasMaxLength(512);

                    b.Property<string>("DescriptionDetailText")
                        .HasMaxLength(512);

                    b.Property<string>("ImageAlt")
                        .HasMaxLength(512);

                    b.Property<string>("ImageDetailText")
                        .HasMaxLength(512);

                    b.Property<string>("ImageSrc")
                        .HasMaxLength(512);

                    b.Property<int?>("Language");

                    b.Property<string>("LinkStoreContent")
                        .HasMaxLength(512);

                    b.Property<string>("LinkStoreHeader")
                        .HasMaxLength(512);

                    b.Property<string>("ProductDetailText")
                        .HasMaxLength(512);

                    b.Property<int?>("ProductId");

                    b.Property<string>("ReviewText")
                        .HasMaxLength(512);

                    b.Property<string>("TitleTagForSEO")
                        .HasMaxLength(512);

                    b.Property<string>("TitleText")
                        .HasMaxLength(512);

                    b.Property<string>("TypeName")
                        .HasMaxLength(512);

                    b.Property<string>("VideoDetailAlt")
                        .HasMaxLength(512);

                    b.Property<string>("VideoDetailSrc")
                        .HasMaxLength(512);

                    b.Property<string>("VideoDetailText")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductLanguage");
                });

            modelBuilder.Entity("HTActive.Entities.ProductLanguageDescriptionDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content")
                        .HasMaxLength(512);

                    b.Property<int?>("ProductLanguageId");

                    b.Property<string>("Title")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.HasIndex("ProductLanguageId");

                    b.ToTable("ProductLanguageDescriptionDetail");
                });

            modelBuilder.Entity("HTActive.Entities.ProductLanguageImageDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Alt")
                        .HasMaxLength(512);

                    b.Property<int?>("ProductLanguageId");

                    b.Property<string>("Src")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.HasIndex("ProductLanguageId");

                    b.ToTable("ProductLanguageImageDetail");
                });

            modelBuilder.Entity("HTActive.Entities.ProductLanguageLinkStore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Link")
                        .HasMaxLength(512);

                    b.Property<int?>("ProductLanguageId");

                    b.Property<string>("Text")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.HasIndex("ProductLanguageId");

                    b.ToTable("ProductLanguageLinkStore");
                });

            modelBuilder.Entity("HTActive.Entities.ProductLanguageProductDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content")
                        .HasMaxLength(2048);

                    b.Property<string>("Header")
                        .HasMaxLength(512);

                    b.Property<int?>("Priority");

                    b.Property<int?>("ProductLanguageId");

                    b.HasKey("Id");

                    b.HasIndex("ProductLanguageId");

                    b.ToTable("ProductLanguageProductDetail");
                });

            modelBuilder.Entity("HTActive.Entities.ProductLanguageReviewDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Detail")
                        .HasMaxLength(512);

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(512);

                    b.Property<int?>("ProductLanguageId");

                    b.Property<string>("RateDate")
                        .HasMaxLength(512);

                    b.Property<float>("RateScore")
                        .HasMaxLength(512);

                    b.Property<string>("Title")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.HasIndex("ProductLanguageId");

                    b.ToTable("ProductLanguageReviewDetail");
                });

            modelBuilder.Entity("HTActive.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256);

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<int>("RoleType");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("HTActive.Entities.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ClaimId");

                    b.Property<int?>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaim");
                });

            modelBuilder.Entity("HTActive.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Priority");

                    b.Property<int?>("ServiceType");

                    b.HasKey("Id");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("HTActive.Entities.ServiceLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(1024);

                    b.Property<string>("ImageAlt")
                        .HasMaxLength(512);

                    b.Property<string>("ImageSrc")
                        .HasMaxLength(512);

                    b.Property<int>("Language");

                    b.Property<int?>("ServiceId");

                    b.Property<string>("TitleTagForSEO")
                        .HasMaxLength(512);

                    b.Property<string>("TitleText")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceLanguage");
                });

            modelBuilder.Entity("HTActive.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateDate");

                    b.Property<string>("Password")
                        .HasMaxLength(256);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(256);

                    b.Property<string>("ProviderName")
                        .HasMaxLength(256);

                    b.Property<DateTime?>("UpdatedDate");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<int?>("UserStatusId");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("HTActive.Entities.UserLoginToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ExpiredDated");

                    b.Property<bool?>("IsRememberMe");

                    b.Property<DateTime>("LastLoginDated");

                    b.Property<string>("Token")
                        .HasMaxLength(256);

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserLoginToken");
                });

            modelBuilder.Entity("HTActive.Entities.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .HasMaxLength(256);

                    b.Property<int?>("AvatarId");

                    b.Property<string>("City")
                        .HasMaxLength(256);

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<string>("FirstName")
                        .HasMaxLength(256);

                    b.Property<string>("LastName")
                        .HasMaxLength(256);

                    b.Property<int?>("UserId");

                    b.Property<bool?>("WasVerifiedEmail");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.HasIndex("UserId");

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("HTActive.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("RoleId");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("HTActive.Entities.ContentIndexAboutUsRight", b =>
                {
                    b.HasOne("HTActive.Entities.ContentIndex", "ContentIndex")
                        .WithMany("AboutUsRights")
                        .HasForeignKey("ContentIndexId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HTActive.Entities.ContentIndexFeature", b =>
                {
                    b.HasOne("HTActive.Entities.ContentIndex", "ContentIndex")
                        .WithMany("Features")
                        .HasForeignKey("ContentIndexId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HTActive.Entities.ContentIndexTopSlide", b =>
                {
                    b.HasOne("HTActive.Entities.ContentIndex", "ContentIndex")
                        .WithMany("TopSlides")
                        .HasForeignKey("ContentIndexId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HTActive.Entities.ContentIndexWhyChoose", b =>
                {
                    b.HasOne("HTActive.Entities.ContentIndex", "ContentIndex")
                        .WithMany("WhyChooseReasons")
                        .HasForeignKey("ContentIndexId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HTActive.Entities.ContentMenu", b =>
                {
                    b.HasOne("HTActive.Entities.ContentFooter", "ContentFooter")
                        .WithMany("ContentMenus")
                        .HasForeignKey("ContentFooterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HTActive.Entities.ContentServicePartition", b =>
                {
                    b.HasOne("HTActive.Entities.ContentService", "ContentService")
                        .WithMany("ContentServicePartitions")
                        .HasForeignKey("ContentServiceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HTActive.Entities.NewsLanguage", b =>
                {
                    b.HasOne("HTActive.Entities.News", "News")
                        .WithMany("NewsLanguages")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HTActive.Entities.NewsLanguageImage", b =>
                {
                    b.HasOne("HTActive.Entities.NewsLanguage", "NewsLanguage")
                        .WithMany("NewsLanguageImages")
                        .HasForeignKey("NewsLanguageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HTActive.Entities.ProductLanguage", b =>
                {
                    b.HasOne("HTActive.Entities.Product", "Product")
                        .WithMany("ProductLanguages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HTActive.Entities.ProductLanguageDescriptionDetail", b =>
                {
                    b.HasOne("HTActive.Entities.ProductLanguage", "ProductLanguage")
                        .WithMany("ProductLanguageDescriptionDetails")
                        .HasForeignKey("ProductLanguageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HTActive.Entities.ProductLanguageImageDetail", b =>
                {
                    b.HasOne("HTActive.Entities.ProductLanguage", "ProductLanguage")
                        .WithMany("ImageDetails")
                        .HasForeignKey("ProductLanguageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HTActive.Entities.ProductLanguageLinkStore", b =>
                {
                    b.HasOne("HTActive.Entities.ProductLanguage", "ProductLanguage")
                        .WithMany("LinkStores")
                        .HasForeignKey("ProductLanguageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HTActive.Entities.ProductLanguageProductDetail", b =>
                {
                    b.HasOne("HTActive.Entities.ProductLanguage", "ProductLanguage")
                        .WithMany("ProductLanguageProductDetails")
                        .HasForeignKey("ProductLanguageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HTActive.Entities.ProductLanguageReviewDetail", b =>
                {
                    b.HasOne("HTActive.Entities.ProductLanguage", "ProductLanguage")
                        .WithMany("ProductLanguageReviewDetails")
                        .HasForeignKey("ProductLanguageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HTActive.Entities.RoleClaim", b =>
                {
                    b.HasOne("HTActive.Entities.Claim", "Claim")
                        .WithMany("RoleClaims")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HTActive.Entities.Role", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HTActive.Entities.ServiceLanguage", b =>
                {
                    b.HasOne("HTActive.Entities.Service", "Service")
                        .WithMany("ServiceLanguages")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HTActive.Entities.UserLoginToken", b =>
                {
                    b.HasOne("HTActive.Entities.User", "User")
                        .WithMany("UserLoginTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HTActive.Entities.UserProfile", b =>
                {
                    b.HasOne("HTActive.Entities.Image", "Image")
                        .WithMany()
                        .HasForeignKey("AvatarId");

                    b.HasOne("HTActive.Entities.User", "User")
                        .WithMany("UserProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HTActive.Entities.UserRole", b =>
                {
                    b.HasOne("HTActive.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId");

                    b.HasOne("HTActive.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
